# Generated by Django 6.1.1 on 2026-10-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Mobile_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('pin_code', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Payment_method', models.CharField(max_length=10)),
            ],
        ),
    ]
